### ISSUE TITLE
support for libav (ffmpeg is not in ubuntu 14.04)

### ISSUE THREAD

**Issue by brewsterkahle** [sampsyo/audioread#17]
it would be handy if this package supported libav as well as ffmpeg as ubuntu does not support ffmpeg in recent versions.     I understand there are slight calling differences.

(and thank you for this package!)

-brewster
Internet Archive

**Comment by bspeice** [comment]
After playing a bit with a personal project, it appears that `avconv` can be used as a drop-in replacement for FFMPEG. Just use `avconv` instead of `ffmpeg` for any configurations, and you should be good to go.

My configuration for context:
```
convert:
    max_bitrate: 192
    command: avconv -i $source -y -vn -aq 2 $dest
    extension: mp3
```

You will need to install `libav-tools` in order to use `avconv`.
